### ISSUE TITLE
ns3/gtk-config-store.h: No such file or directory

### ISSUE THREAD

**Issue by AlbertoAlos** [Vivek-anand-jain/Reproduce-TCP-BBR-in-ns-3#1]
Hi all,

I am new in ns. When I try to reproduce your results, in the building step "./waf", the compilation stops and the next error message comes up:

../scratch/tcp-bbr-exam.cc:3:34: fatal error: ns3/gtk-config-store.h: No such file or directory

Am I skipping some step? It seems that the header file is not in the repo.

Thanks in advance,

Alberto

**Comment by Vivek-anand-jain** [comment]
Hi Alberto,

Yes, you might have not installed the GTK dependency.

If you are using Ubuntu, you can install following packages.

```
sudo apt-get install libgtk2.0-0 libgtk2.0-dev
```

For more information, you can refer ns-3 installation manual.

After this, you can do:
```
./waf configure && ./waf
```
Hope this helps.
