### ISSUE TITLE
How to visualize the results?I could only use wireshark to visualize the rtt of p-2-0.pcap? I want to map the results of the paper.

### ISSUE THREAD

**Issue by YangYangGirl** [Vivek-anand-jain/Reproduce-TCP-BBR-in-ns-3#2]

**Comment by YangYangGirl** [comment]
![image](https://user-images.githubusercontent.com/32426369/71913440-619f7000-31b2-11ea-95e1-a5bbfaf02658.png)
![image](https://user-images.githubusercontent.com/32426369/71913452-67955100-31b2-11ea-99bd-77b346e8caf9.png)
![image](https://user-images.githubusercontent.com/32426369/71913574-b8a54500-31b2-11ea-93ed-ed34c8a4e8cb.png)

**Comment by Vivek-anand-jain** [comment]
Hi, the results are generated in `results` directory. You can use gnuplot to plot them.
