### ISSUE TITLE
Hello Vivek-anand-jain

### ISSUE THREAD

**Issue by gatherheart** [Vivek-anand-jain/Reproduce-TCP-BBR-in-ns-3#3]
Hello there

I found your repo and tried your BBR simulation.
I tested it many times in my environment, but the result was quite different with your white paper.

nLeaf 1
bandwidth 10Mbps
delay  18ms
access_bandwidth 40Mbps
access_delay 1ms
mtu 536
data  0.000000
error_p 0
qSize 950000
scenario 1
initialCwnd  10
minRto 0.2
transport_prot ns3::TcpBbr

About estimated RTT with the first given configuration, the average of RTT is somewhat higher than yours ( Estimated RTProp is more than 80ms. However Yours is less than 60ms)

![image](https://user-images.githubusercontent.com/40990613/73607202-91e1ff00-45f6-11ea-8adf-4eed2bc918bd.png)

![image](https://user-images.githubusercontent.com/40990613/73607310-d02bee00-45f7-11ea-9ada-a2e357a6e048.png)

Did you understand about these situation?
I cannot found the reason why this happened even after checking your BBR src code.

Thanks

**Comment by Vivek-anand-jain** [comment]
Could you please uncomment this line https://github.com/Vivek-anand-jain/Reproduce-TCP-BBR-in-ns-3/blob/master/src/internet/model/tcp-bbr.cc#L622 and comment the next line to it and then try to check if it is working for you?

**Comment by gatherheart** [comment]
I changed the line as you said
`m_maxBwFilter = MaxBandwidthFilter_t (m_bandwidthWindowLength,
                                            DataRate (tcb->m_initialCWnd * tcb->m_segmentSize * 8 / m_rtProp.GetSeconds ()), 0);`
`//    m_maxBwFilter = MaxBandwidthFilter_t (m_bandwidthWindowLength, DataRate (0), 0);
`

Then, Here is the result.

![image](https://user-images.githubusercontent.com/40990613/73950976-37230d00-4940-11ea-92d1-4b0981a0fc1c.png)

When considering the configured propagation delay, it is to be close to 40ms, but it is not.

Only the thing i changed is the comment line. 
Do you have any idea to solve this problem?

**Comment by gatherheart** [comment]
There is one more thing i want to let you know.

I made another NS3 simulation code for testing dumbbell topology with your BBR code.

Here is the result.
![image](https://user-images.githubusercontent.com/40990613/73953894-6176c980-4944-11ea-8db6-caa98d5fdca5.png)

It found almost minimum RTT, but the shape is quite different with yours and google's and not consistent.
Moreover, originally every 10 seconds RTT should be changed but this result is not showing that.

Please refer to this result.

**Comment by Vivek-anand-jain** [comment]
Sorry for the delay. Are you generating background traffic? What topology are you using?
The Google's paper mentioned presence of some background traffic but they did not mention the source and pattern of the traffic that might be the reason behind this discrepancy.

**Comment by gatherheart** [comment]
No Problem.

1. No I am not. I did not generate any background traffic. 

2. At first, I used dumbbell topology codes. 
1) http://personal.ee.surrey.ac.uk/Personal/K.Katsaros/media/ns3lab-sol/lab-2-solved.cc
2) https://github.com/mark-claypool/bbr/blob/master/bbr-tests/bulk.cc
3) and your tcp-bbr-exam.cc
4) my dumbbell topology code which is similar to first one.

the congestion control algorithm of all the sources is changed into your BBR code,
which is at src/internet/model/tcp-bbr.cc
Moreover, the condition is same with yours, propagation delay and bottleneck BW, access BW.

All the results are similar to the first result.

I show you some results.

** Your Dumbbell Topology with Your BBR code **
![image](https://user-images.githubusercontent.com/40990613/73950976-37230d00-4940-11ea-92d1-4b0981a0fc1c.png)

** 1) Dumbbell Topology with Your BBR code **
![image](https://user-images.githubusercontent.com/40990613/76139792-27116100-6097-11ea-8c28-dcd4f68b8aad.png)

![image](https://user-images.githubusercontent.com/40990613/76277189-56a8af00-62cb-11ea-98d7-aa582a6c996c.png)


** 1) Dumbbell Topology with Your BBR code which is changed with the way you told. **
`m_maxBwFilter = MaxBandwidthFilter_t (m_bandwidthWindowLength, DataRate (tcb->m_initialCWnd * tcb->m_segmentSize * 8 / m_rtProp.GetSeconds ()), 0);
// m_maxBwFilter = MaxBandwidthFilter_t (m_bandwidthWindowLength, DataRate (0), 0);`

![image](https://user-images.githubusercontent.com/40990613/76139897-55437080-6098-11ea-943d-a65fc2158a5d.png)

** 1) Dumbbell Topology with other BBR code which is from https://github.com/mark-claypool/bbr. **
![image](https://user-images.githubusercontent.com/40990613/76140016-85d7da00-6099-11ea-8bb8-8128ba29381f.png)

![image](https://user-images.githubusercontent.com/40990613/76277287-adae8400-62cb-11ea-90f1-d8f374c523ab.png)

I'm trying to correct this problem. However it is not quite easy.
Do you know the reason why this results happen?

**Comment by gatherheart** [comment]
I think the problem is that the algorithm with your bbr code could not use the RTProp properly during PROBE_BW stage.
